import { Merchant, MerchantListing } from '@/types';

// Mock Merchants Data
export const mockMerchants: Merchant[] = [
  {
    merchant_id: 1,
    merchant_name: 'Serena Hotel Kigali',
    merchant_types: ['hotel', 'restaurant', 'venue'],
    business_email: 'info@serenahotel.rw',
    business_phone: '+250788123456',
    business_address: 'KN 3 Ave, Kigali City Center',
    business_description: 'Luxury 5-star hotel in the heart of Kigali with world-class amenities, fine dining restaurants, and conference facilities.',
    tax_id: 'TAX001KGL',
    license_number: 'HTL-RW-001',
    rating: 4.8,
    total_reviews: 245,
    total_listings: 8,
    status: 'active',
    created_date: '2023-01-15T10:00:00Z',
    updated_date: '2024-11-10T14:30:00Z',
  },
  {
    merchant_id: 2,
    merchant_name: 'Heaven Restaurant & Boutique Hotel',
    merchant_types: ['restaurant', 'hotel'],
    business_email: 'contact@heavenrestaurant.rw',
    business_phone: '+250788234567',
    business_address: 'KG 7 Ave, Kimihurura, Kigali',
    business_description: 'Fine dining restaurant offering international cuisine with a beautiful city view, plus boutique accommodation.',
    tax_id: 'TAX002KGL',
    license_number: 'RST-RW-002',
    rating: 4.5,
    total_reviews: 189,
    total_listings: 5,
    status: 'active',
    created_date: '2023-03-20T09:00:00Z',
    updated_date: '2024-11-08T16:20:00Z',
  },
  {
    merchant_id: 3,
    merchant_name: 'Kigali Convention Center',
    merchant_types: ['venue', 'restaurant', 'service'],
    business_email: 'bookings@kcc.rw',
    business_phone: '+250788345678',
    business_address: 'KN 4 Ave, Kigali Heights',
    business_description: 'State-of-the-art conference and event center with multiple halls, meeting rooms, and full-service catering.',
    tax_id: 'TAX003KGL',
    license_number: 'VEN-RW-001',
    rating: 4.7,
    total_reviews: 156,
    total_listings: 6,
    status: 'active',
    created_date: '2022-11-10T08:00:00Z',
    updated_date: '2024-11-11T10:15:00Z',
  },
  {
    merchant_id: 4,
    merchant_name: 'Lake Kivu Serena Hotel',
    merchant_types: ['hotel', 'restaurant', 'venue', 'service'],
    business_email: 'lakeserena@serenahotel.rw',
    business_phone: '+250788456789',
    business_address: 'Rubavu, Lake Kivu Waterfront',
    business_description: 'Beautiful lakeside resort hotel with stunning views, premium facilities, water sports, and event spaces.',
    tax_id: 'TAX004RBV',
    license_number: 'HTL-RW-004',
    rating: 4.6,
    total_reviews: 198,
    total_listings: 10,
    status: 'active',
    created_date: '2023-02-05T11:00:00Z',
    updated_date: '2024-11-09T13:45:00Z',
  },
  {
    merchant_id: 5,
    merchant_name: 'The Hut Restaurant',
    merchant_types: ['restaurant'],
    business_email: 'info@thehut.rw',
    business_phone: '+250788567890',
    business_address: 'KG 5 Ave, Kacyiru, Kigali',
    business_description: 'Cozy restaurant serving authentic Rwandan cuisine and international dishes in a traditional setting.',
    tax_id: 'TAX005KGL',
    license_number: 'RST-RW-005',
    rating: 4.3,
    total_reviews: 134,
    total_listings: 3,
    status: 'active',
    created_date: '2023-05-12T10:30:00Z',
    updated_date: '2024-11-07T15:00:00Z',
  },
  {
    merchant_id: 6,
    merchant_name: 'Kigali Marriott Hotel',
    merchant_types: ['hotel', 'restaurant', 'venue'],
    business_email: 'reservations@marriottkigali.rw',
    business_phone: '+250788678901',
    business_address: 'KN 3 Ave, City Center, Kigali',
    business_description: 'International luxury hotel brand with modern facilities, multiple dining options, and conference rooms.',
    tax_id: 'TAX006KGL',
    license_number: 'HTL-RW-006',
    rating: 4.7,
    total_reviews: 312,
    total_listings: 12,
    status: 'active',
    created_date: '2022-08-20T09:00:00Z',
    updated_date: '2024-11-10T11:30:00Z',
  },
  {
    merchant_id: 7,
    merchant_name: 'Inema Arts Center',
    merchant_types: ['venue', 'shop', 'service'],
    business_email: 'events@inemaartcenter.rw',
    business_phone: '+250788789012',
    business_address: 'KG 563 St, Kacyiru, Kigali',
    business_description: 'Contemporary art gallery and event space with art shop and workshops.',
    tax_id: 'TAX007KGL',
    license_number: 'VEN-RW-007',
    rating: 4.4,
    total_reviews: 87,
    total_listings: 4,
    status: 'active',
    created_date: '2023-04-18T12:00:00Z',
    updated_date: '2024-11-06T14:20:00Z',
  },
  {
    merchant_id: 8,
    merchant_name: 'Virunga Eco Tours',
    merchant_types: ['service', 'shop'],
    business_email: 'info@virungaecotours.rw',
    business_phone: '+250788890123',
    business_address: 'KN 2 Ave, Musanze',
    business_description: 'Premium eco-tourism services including gorilla trekking, hiking tours, and local crafts shop.',
    tax_id: 'TAX008MSZ',
    license_number: 'SRV-RW-008',
    rating: 4.9,
    total_reviews: 276,
    total_listings: 7,
    status: 'active',
    created_date: '2022-12-01T08:30:00Z',
    updated_date: '2024-11-11T09:00:00Z',
  },
  {
    merchant_id: 9,
    merchant_name: 'Repub Lounge',
    merchant_types: ['restaurant', 'venue'],
    business_email: 'bookings@republounge.rw',
    business_phone: '+250788901234',
    business_address: 'KG 9 Ave, Nyarutarama, Kigali',
    business_description: 'Upscale lounge and restaurant with event hosting capabilities for private parties.',
    tax_id: 'TAX009KGL',
    license_number: 'RST-RW-009',
    rating: 4.2,
    total_reviews: 156,
    total_listings: 4,
    status: 'active',
    created_date: '2023-06-25T11:00:00Z',
    updated_date: '2024-11-08T12:30:00Z',
  },
  {
    merchant_id: 10,
    merchant_name: 'Azizi Life Crafts',
    merchant_types: ['shop', 'service'],
    business_email: 'shop@azizilife.rw',
    business_phone: '+250789012345',
    business_address: 'KN 15 Ave, Kigali',
    business_description: 'Authentic Rwandan crafts shop with cultural immersion experiences and workshops.',
    tax_id: 'TAX010KGL',
    license_number: 'SHP-RW-010',
    rating: 4.6,
    total_reviews: 93,
    total_listings: 15,
    status: 'active',
    created_date: '2023-07-10T10:00:00Z',
    updated_date: '2024-11-05T16:00:00Z',
  },
  {
    merchant_id: 11,
    merchant_name: 'New Cleo Hotel & Spa',
    merchant_types: ['hotel', 'service'],
    business_email: 'info@newcleohotel.rw',
    business_phone: '+250789123456',
    business_address: 'KG 11 Ave, Remera, Kigali',
    business_description: 'Modern hotel with full-service spa and wellness center.',
    tax_id: 'TAX011KGL',
    license_number: 'HTL-RW-011',
    rating: 4.4,
    total_reviews: 167,
    total_listings: 6,
    status: 'pending',
    created_date: '2024-10-15T09:00:00Z',
  },
  {
    merchant_id: 12,
    merchant_name: 'Akagera Game Lodge',
    merchant_types: ['hotel', 'restaurant', 'service'],
    business_email: 'reservations@akageragamelodge.rw',
    business_phone: '+250789234567',
    business_address: 'Akagera National Park, Eastern Province',
    business_description: 'Safari lodge with restaurant and guided wildlife tours in Akagera National Park.',
    tax_id: 'TAX012AKG',
    license_number: 'HTL-RW-012',
    rating: 4.8,
    total_reviews: 203,
    total_listings: 5,
    status: 'active',
    created_date: '2023-01-30T07:00:00Z',
    updated_date: '2024-11-09T10:45:00Z',
  },
];

// Mock Merchant Listings Data
export const mockMerchantListings: MerchantListing[] = [
  // Serena Hotel Kigali (merchant_id: 1)
  {
    listing_id: 1,
    merchant_id: 1,
    listing_type: 'hotel',
    listing_name: 'Standard Room',
    description: 'Comfortable room with queen bed, ensuite bathroom, and city view. Includes free Wi-Fi, air conditioning, and flat-screen TV.',
    price: 150000,
    currency: 'RWF',
    category: 'Standard',
    capacity: 2,
    availability: 'available',
    rating: 4.5,
    reviews_count: 89,
    status: 'active',
    created_date: '2023-01-15T10:00:00Z',
    updated_date: '2024-11-10T14:30:00Z',
  },
  {
    listing_id: 2,
    merchant_id: 1,
    listing_type: 'hotel',
    listing_name: 'Deluxe Suite',
    description: 'Spacious suite with king bed, living area, work desk, and premium amenities. Beautiful city views.',
    price: 300000,
    currency: 'RWF',
    category: 'Deluxe',
    capacity: 2,
    availability: 'available',
    rating: 4.9,
    reviews_count: 67,
    status: 'active',
    created_date: '2023-01-15T10:00:00Z',
    updated_date: '2024-11-10T14:30:00Z',
  },
  {
    listing_id: 3,
    merchant_id: 1,
    listing_type: 'hotel',
    listing_name: 'Presidential Suite',
    description: 'Luxurious presidential suite with panoramic views, separate living room, dining area, and exclusive butler service.',
    price: 600000,
    currency: 'RWF',
    category: 'Premium',
    capacity: 4,
    availability: 'available',
    rating: 5.0,
    reviews_count: 23,
    status: 'active',
    created_date: '2023-01-15T10:00:00Z',
    updated_date: '2024-11-10T14:30:00Z',
  },
  {
    listing_id: 4,
    merchant_id: 1,
    listing_type: 'restaurant',
    listing_name: 'Milima Restaurant - Table Reservation',
    description: 'Fine dining experience at our signature restaurant. Reservation includes table for duration of meal.',
    price: 0,
    currency: 'RWF',
    category: 'Fine Dining',
    capacity: 4,
    availability: 'available',
    rating: 4.7,
    reviews_count: 145,
    status: 'active',
    created_date: '2023-01-15T10:00:00Z',
  },
  {
    listing_id: 5,
    merchant_id: 1,
    listing_type: 'venue',
    listing_name: 'Conference Hall A',
    description: 'Professional conference hall with capacity for 100 people. Includes AV equipment, projector, and high-speed internet.',
    price: 250000,
    currency: 'RWF',
    category: 'Conference',
    capacity: 100,
    availability: 'available',
    rating: 4.6,
    reviews_count: 34,
    status: 'active',
    created_date: '2023-01-15T10:00:00Z',
  },

  // Heaven Restaurant (merchant_id: 2)
  {
    listing_id: 6,
    merchant_id: 2,
    listing_type: 'restaurant',
    listing_name: 'Indoor Table for 2',
    description: 'Intimate table for two in our elegant main dining area with city views.',
    price: 0,
    currency: 'RWF',
    category: 'Standard',
    capacity: 2,
    availability: 'available',
    rating: 4.4,
    reviews_count: 45,
    status: 'active',
    created_date: '2023-03-20T09:00:00Z',
  },
  {
    listing_id: 7,
    merchant_id: 2,
    listing_type: 'restaurant',
    listing_name: 'Terrace Table for 4',
    description: 'Outdoor terrace table with panoramic city views. Perfect for special occasions.',
    price: 10000,
    currency: 'RWF',
    category: 'Premium',
    capacity: 4,
    availability: 'available',
    rating: 4.8,
    reviews_count: 56,
    status: 'active',
    created_date: '2023-03-20T09:00:00Z',
  },
  {
    listing_id: 8,
    merchant_id: 2,
    listing_type: 'restaurant',
    listing_name: 'Private Dining Room',
    description: 'Exclusive private dining room for special occasions and business dinners. Includes dedicated server.',
    price: 50000,
    currency: 'RWF',
    category: 'VIP',
    capacity: 8,
    availability: 'available',
    rating: 4.9,
    reviews_count: 28,
    status: 'active',
    created_date: '2023-03-20T09:00:00Z',
  },
  {
    listing_id: 9,
    merchant_id: 2,
    listing_type: 'hotel',
    listing_name: 'Boutique Room',
    description: 'Stylish boutique room with modern amenities and unique decor.',
    price: 120000,
    currency: 'RWF',
    category: 'Boutique',
    capacity: 2,
    availability: 'available',
    rating: 4.5,
    reviews_count: 60,
    status: 'active',
    created_date: '2023-03-20T09:00:00Z',
  },

  // Kigali Convention Center (merchant_id: 3)
  {
    listing_id: 10,
    merchant_id: 3,
    listing_type: 'venue',
    listing_name: 'Main Conference Hall',
    description: 'Large conference hall with seating for up to 500 people. Full AV equipment, stage, and professional sound system.',
    price: 500000,
    currency: 'RWF',
    category: 'Large',
    capacity: 500,
    availability: 'available',
    rating: 4.8,
    reviews_count: 56,
    status: 'active',
    created_date: '2022-11-10T08:00:00Z',
  },
  {
    listing_id: 11,
    merchant_id: 3,
    listing_type: 'venue',
    listing_name: 'Meeting Room A',
    description: 'Medium-sized meeting room perfect for corporate meetings and workshops.',
    price: 150000,
    currency: 'RWF',
    category: 'Medium',
    capacity: 30,
    availability: 'available',
    rating: 4.6,
    reviews_count: 34,
    status: 'active',
    created_date: '2022-11-10T08:00:00Z',
  },
  {
    listing_id: 12,
    merchant_id: 3,
    listing_type: 'venue',
    listing_name: 'Meeting Room B',
    description: 'Small meeting room ideal for board meetings and team discussions.',
    price: 80000,
    currency: 'RWF',
    category: 'Small',
    capacity: 15,
    availability: 'available',
    rating: 4.5,
    reviews_count: 28,
    status: 'active',
    created_date: '2022-11-10T08:00:00Z',
  },
  {
    listing_id: 13,
    merchant_id: 3,
    listing_type: 'service',
    listing_name: 'Full Catering Service',
    description: 'Professional catering service for events. Menu customization available.',
    price: 15000,
    currency: 'RWF',
    category: 'Catering',
    capacity: 500,
    availability: 'available',
    rating: 4.7,
    reviews_count: 42,
    status: 'active',
    created_date: '2022-11-10T08:00:00Z',
  },

  // Lake Kivu Serena Hotel (merchant_id: 4)
  {
    listing_id: 14,
    merchant_id: 4,
    listing_type: 'hotel',
    listing_name: 'Lakeside Standard Room',
    description: 'Room with direct lake view and private balcony. Wake up to beautiful sunrise over Lake Kivu.',
    price: 180000,
    currency: 'RWF',
    category: 'Standard',
    capacity: 2,
    availability: 'available',
    rating: 4.7,
    reviews_count: 78,
    status: 'active',
    created_date: '2023-02-05T11:00:00Z',
  },
  {
    listing_id: 15,
    merchant_id: 4,
    listing_type: 'hotel',
    listing_name: 'Family Suite',
    description: 'Spacious suite with two bedrooms, perfect for families. Lake view and children-friendly amenities.',
    price: 350000,
    currency: 'RWF',
    category: 'Family',
    capacity: 4,
    availability: 'available',
    rating: 4.6,
    reviews_count: 45,
    status: 'active',
    created_date: '2023-02-05T11:00:00Z',
  },
  {
    listing_id: 16,
    merchant_id: 4,
    listing_type: 'service',
    listing_name: 'Water Sports Package',
    description: 'Full day water sports activities including kayaking, paddleboarding, and boat tours.',
    price: 50000,
    currency: 'RWF',
    category: 'Activities',
    capacity: 10,
    availability: 'available',
    rating: 4.8,
    reviews_count: 67,
    status: 'active',
    created_date: '2023-02-05T11:00:00Z',
  },

  // The Hut Restaurant (merchant_id: 5)
  {
    listing_id: 17,
    merchant_id: 5,
    listing_type: 'restaurant',
    listing_name: 'Outdoor Terrace Table',
    description: 'Table on our beautiful outdoor terrace with traditional Rwandan ambiance.',
    price: 0,
    currency: 'RWF',
    category: 'Standard',
    capacity: 4,
    availability: 'available',
    rating: 4.3,
    reviews_count: 67,
    status: 'active',
    created_date: '2023-05-12T10:30:00Z',
  },
  {
    listing_id: 18,
    merchant_id: 5,
    listing_type: 'restaurant',
    listing_name: 'Traditional Rwandan Set Menu',
    description: 'Experience authentic Rwandan cuisine with our special set menu featuring local delicacies.',
    price: 25000,
    currency: 'RWF',
    category: 'Set Menu',
    capacity: 1,
    availability: 'available',
    rating: 4.7,
    reviews_count: 89,
    status: 'active',
    created_date: '2023-05-12T10:30:00Z',
  },

  // Virunga Eco Tours (merchant_id: 8)
  {
    listing_id: 19,
    merchant_id: 8,
    listing_type: 'service',
    listing_name: 'Gorilla Trekking Tour',
    description: 'Full day guided gorilla trekking experience in Volcanoes National Park. Includes transport and packed lunch.',
    price: 1500,
    currency: 'USD',
    category: 'Premium Tour',
    capacity: 8,
    availability: 'available',
    rating: 5.0,
    reviews_count: 156,
    status: 'active',
    created_date: '2022-12-01T08:30:00Z',
  },
  {
    listing_id: 20,
    merchant_id: 8,
    listing_type: 'service',
    listing_name: 'Golden Monkey Trekking',
    description: 'Half day golden monkey tracking adventure with experienced guides.',
    price: 100,
    currency: 'USD',
    category: 'Standard Tour',
    capacity: 12,
    availability: 'available',
    rating: 4.8,
    reviews_count: 89,
    status: 'active',
    created_date: '2022-12-01T08:30:00Z',
  },
  {
    listing_id: 21,
    merchant_id: 8,
    listing_type: 'shop',
    listing_name: 'Handmade Rwandan Basket',
    description: 'Traditional handwoven basket made by local artisans. Various sizes and designs available.',
    price: 45000,
    currency: 'RWF',
    category: 'Crafts',
    capacity: 1,
    availability: 'available',
    rating: 4.6,
    reviews_count: 34,
    status: 'active',
    created_date: '2022-12-01T08:30:00Z',
  },
];

// Helper function to get listings by merchant ID
export function getListingsByMerchantId(merchantId: number): MerchantListing[] {
  return mockMerchantListings.filter(listing => listing.merchant_id === merchantId);
}

// Helper function to get merchant by ID
export function getMerchantById(merchantId: number): Merchant | undefined {
  return mockMerchants.find(merchant => merchant.merchant_id === merchantId);
}

